import React, { useState } from 'react';
import { X, Download, Copy, Check, FileDown } from 'lucide-react';
import { AudioAnalysisResult, DetectedPause, FillerWordItem, WrongWordItem } from '../types/audio';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: AudioAnalysisResult;
  transcriptText: string;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  result,
  transcriptText,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const reportMarkdown = `# Speech & Audio Analytics Audit Report
Generated by AudioPulse Dashboard
Date: ${new Date().toLocaleString()}

## Key Metrics
- Audio Duration: ${result.durationSeconds.toFixed(1)} seconds
- Total Words: ${result.wordCount}
- Speaking Speed: ${result.wpm} WPM (${result.detectedPaceCategory})
- Overall Fluency Score: ${result.fluencyScore} / 100
- Clarity Score: ${result.clarityScore} / 100
- Total Pauses & Silences: ${result.pauses.length} (${result.totalSilenceSeconds.toFixed(1)}s total)

## Wrong Words & Stumbles Detected (${result.wrongWords.length})
${result.wrongWords.map((w, i) => `${i + 1}. "${w.word}" - ${w.issue}: ${w.suggestion}`).join('\n') || 'None'}

## Filler Words Frequency (${result.fillerWords.reduce((a, b) => a + b.count, 0)})
${result.fillerWords.map((f) => `- "${f.word}": ${f.count} times (${f.percentage}%)`).join('\n') || 'None'}

## Pauses Assessment
- Total Awkward Pauses (>1.2s): ${result.pausesEvaluation.totalAwkwardPauses}
- Assessment: ${result.pausesEvaluation.assessment}
- Pacing Advice: ${result.pausesEvaluation.advice}

## Speech Coach Tips
${result.actionableTips.map((tip, i) => `${i + 1}. ${tip}`).join('\n')}

## Synchronized Transcript
${transcriptText || '(No transcript available)'}
`;

  const downloadReport = () => {
    const blob = new Blob([reportMarkdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AudioPulse-Report-${Date.now()}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-xl w-full max-w-xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950/70">
          <div className="flex items-center gap-2">
            <FileDown className="w-4 h-4 text-cyan-400" />
            <h2 className="text-sm font-bold text-white tracking-tight">
              Export Speech Analytics Report
            </h2>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="p-6 overflow-y-auto space-y-4 text-xs text-slate-300">
          <p className="text-slate-400">
            Export a full diagnostic summary of pauses, speaking rate, wrong words, filler frequencies, and speech coaching recommendations.
          </p>

          <pre className="p-3 bg-slate-950 border border-slate-800 rounded font-mono text-[11px] text-slate-300 max-h-60 overflow-y-auto leading-relaxed">
            {reportMarkdown}
          </pre>
        </div>

        <div className="px-6 py-3 border-t border-slate-800 bg-slate-950/70 flex items-center justify-between">
          <button
            onClick={copyToClipboard}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded text-xs transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Text'}</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded text-xs transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={downloadReport}
              className="flex items-center gap-1.5 px-4 py-1.5 bg-cyan-600 hover:bg-cyan-500 text-white rounded text-xs font-medium transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Markdown</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
